### PR TITLE
Syncthing: Fix CI e2e

### LINKED ISSUE #306: CI flake: Syncthing e2e
**Describe the bug**
```
    logger.go:42: 13:53:54 | syncthing-cluster-sync/30-kill-syncthing-pods-and-reconnect | starting test step 30-kill-syncthing-pods-and-reconnect
    logger.go:42: 13:53:54 | syncthing-cluster-sync/30-kill-syncthing-pods-and-reconnect | running command: [sh -c set -e -o pipefail
        # import the necessary utils for working w/ Syncthing
        source ./utils.sh
        # delete all of the Syncthing Pods belonging to ReplicationSources
        for k in $(seq 1 2); do
          target_rs="syncthing-${k}"
          # get the previious syncthing peer ID for replicationsource 'syncthing-1'
          prev_st_peer_id="$(kubectl get replicationsource "${target_rs}" -n "${NAMESPACE}" -o jsonpath='{.status.syncthing.ID}')"
          # find the Syncthing pod belonging to the first ReplicationSource 'syncthing-1' and delete it
          syncthing_podname="$(kubectl get pods -l app.kubernetes.io/name="${target_rs}" -n "${NAMESPACE}" -o jsonpath='{.items[0].metadata.name}')"
          kubectl delete pod "${syncthing_podname}" -n "${NAMESPACE}"
          # wait until a new pod is created
          syncthing_new_podname=$(kubectl get pods -l app.kubernetes.io/name="${target_rs}" -n "${NAMESPACE}" -o jsonpath='{.items[0].metadata.name}')
          kubectl wait --for=condition=Ready pod "${syncthing_new_podname}" -n "${NAMESPACE}" --timeout=600s
          # get the new syncthing peer ID for the target replicationsource
          new_st_peer_id=$(kubectl get replicationsource "${target_rs}" -n "${NAMESPACE}" -o jsonpath='{.status.syncthing.ID}')
          # assert that the new syncthing peer ID is the same as the previous one
          if [[ "${prev_st_peer_id}" != "${new_st_peer_id}" ]]; then
            echo "ERROR: new syncthing peer ID is not the same as the previous one"
            exit 1
          fi
        done
        ]
    logger.go:42: 13:53:54 | syncthing-cluster-sync/30-kill-syncthing-pods-and-reconnect | pod "volsync-syncthing-1-69564b4c88-dp6dd" deleted
    logger.go:42: 13:54:05 | syncthing-cluster-sync/30-kill-syncthing-pods-and-reconnect | pod/volsync-syncthing-1-69564b4c88-fqhlm condition met
    logger.go:42: 13:54:05 | syncthing-cluster-sync/30-kill-syncthing-pods-and-reconnect | pod "volsync-syncthing-2-755787c777-bv25v" deleted
    logger.go:42: 13:54:10 | syncthing-cluster-sync/30-kill-syncthing-pods-and-reconnect | error: error executing jsonpath "{.items[0].metadata.name}": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
    logger.go:42: 13:54:10 | syncthing-cluster-sync/30-kill-syncthing-pods-and-reconnect | 	template was:
    logger.go:42: 13:54:10 | syncthing-cluster-sync/30-kill-syncthing-pods-and-reconnect | 		{.items[0].metadata.name}
    logger.go:42: 13:54:10 | syncthing-cluster-sync/30-kill-syncthing-pods-and-reconnect | 	object given to jsonpath engine was:
    logger.go:42: 13:54:10 | syncthing-cluster-sync/30-kill-syncthing-pods-and-reconnect | 		map[string]interface {}{"apiVersion":"v1", "items":[]interface {}{}, "kind":"List", "metadata":map[string]interface {}{"resourceVersion":"", "selfLink":""}}
    logger.go:42: 13:54:10 | syncthing-cluster-sync/30-kill-syncthing-pods-and-reconnect | 
    logger.go:42: 13:54:10 | syncthing-cluster-sync/30-kill-syncthing-pods-and-reconnect | 
    case.go:361: failed in step 30-kill-syncthing-pods-and-reconnect
```

### LINKED ISSUE #309: Syncthing: X509 certificate name mismatch
**Describe the bug**
E2E on OCP failed with:
```
logger.go:42: 18:20:17 | syncthing-cluster-sync/10-connect-syncthings | {"conditions":[{"lastTransitionTime":"2022-07-07T18:10:41Z","message":"Get \"https://volsync-syncthing-1-api.kuttl-test-organic-monitor:8384/rest/config\": x509: certificate is valid for volsync-syncthing-1-88b95999-77b7b, not volsync-syncthing-1-api.kuttl-test-organic-monitor","reason":"Error","status":"False","type":"Synchronizing"}],"lastSyncStartTime":"2022-07-07T18:10:31Z","syncthing":{}}syncthing info not yet available, current status:
```

**Steps to reproduce**

**Expected behavior**

**Actual results**

**Additional context**

It looks like the certificate is being generated for the Pod DNS name, not the Service.

### PR DESCRIPTION
**Pull request by JohnStrunk**
**Describe what this PR does**
Ensures that the `config.xml` file is readable in the mover image.

This is to fix the following (from container logs):
```console
$ kubectl -n kuttl-test-brave-sheepdog logs pod/volsync-syncthing-1-755d844cdb-7trw5
===== STARTING CONTAINER =====
===== VolSync Syncthing container version: v0.5.0+ed1e00f =====
===== run =====
===== Running preflight check =====
===== ensuring necessary variables are defined =====
===== populating /config with /config.xml =====
cp: cannot open '/config.xml' for reading: Permission denied
```

It was causing the mover to CLBO.

- ~This is also attempting to fix #309 by failing if the certs can't be copied from the secret~ Turned out to be a CI config problem
- Attempts to fix #306 by waiting for previous pod to be deleted
- Enables Syncthing backward compatibility w/ TLS 1.2 because the current FIPS-enabled golang builder doesn't support TLS 1.3

**Is there anything that requires special attention?**

**Related issues:**

### CODE REVIEW

File: mover-syncthing/entry.sh [hunk 1]
```diff
@@ -133,8 +129,8 @@ for op in "$@"; do
       # ensure our environment is configured before syncthing runs
       preflight_check
 
-      # launch syncthing			
-      syncthing -home "${SYNCTHING_CONFIG_DIR}"
+      # launch syncthing
+      exec syncthing -home "${SYNCTHING_CONFIG_DIR}" --verbose
```
Comment (JohnStrunk) [inline mover-syncthing/entry.sh:133]: Added the `exec` so that when the Pod receives a shutdown signal, it will be passed to syncthing, giving it a chance to stop cleanly

**Comment by JohnStrunk** [comment]
/retest
Now that openshift/release#30453 is in

**Comment by JohnStrunk** [comment]
/cc @RobotSail 
Looks like these changes are getting OpenShift CI to pass consistently, so it's ready for review.
I really don't like enabling TLS 1.2 (241b574). It'd be good to get a real answer on why this is necessary for us.

**Comment by JohnStrunk** [comment]
Digging a bit further, it seems to be an interaction w/ the FIPS compliant build.

From [CRYPTO-6185](https://issues.redhat.com/browse/CRYPTO-6185):

> Checked with the go 1.18.3 release, these hard-coded algorithms are basically in src/crypto/tls/boring.go:
> - TLS versions: min = TLS 1.2, max = TLS 1.2
> - ...

**Review by RobotSail — APPROVED** [review]
Looks good to me, the TLS 1.2 usage is not at all what I would expect to have been breaking this, but I guess it makes some sense.

The strange thing is that when we investigated the Pod from the other week, the certs were never loaded into the Syncthing container to begin with. Was this born of the same issue?

Nice job on determining the cause of the problem, hopefully we can upgrade to TLS 1.3.
